N, M = tuple(map(int, input().split()))
Ann = set()
Bor = set()
for i_n in range(N):
    Ann.add(int(input()))
for i_m in range(M):
    Bor.add(int(input()))
intrs = sorted(list(Bor.intersection(Ann)))
remBor = sorted(list(Bor.difference(Ann)))
remAnn = sorted(list(Ann.difference(Bor)))
print(intrs.__len__())
print(*intrs)
print(remAnn.__len__())
print(*remAnn)
print(remBor.__len__())
print(*remBor)
